# Generated by Django 5.0.3 on 2024-04-14 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0006_remove_patient_assigneddoctorid_healthdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthdata',
            name='user',
        ),
        migrations.AddField(
            model_name='healthdata',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='health_data', to='health.patient'),
            preserve_default=False,
        ),
    ]
