# Generated by Django 5.0.3 on 2024-04-15 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0007_remove_healthdata_user_healthdata_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.doctor'),
        ),
    ]
