# Generated by Django 5.0.3 on 2024-04-15 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0008_appointment_approved_alter_appointment_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='approved',
            new_name='accepted',
        ),
    ]
