# Generated by Django 5.0.3 on 2024-04-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0010_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthdata',
            name='body_temperature',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='healthdata',
            name='cholestrol_level',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='healthdata',
            name='heart_rate',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
